import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('Firebase Google auth gates chat access and removes manual new-chat registration', () => {
  const app = readFileSync(new URL('../src/app.js', import.meta.url), 'utf8');
  const auth = readFileSync(new URL('../src/firebase-chat.js', import.meta.url), 'utf8');
  const config = readFileSync(new URL('../src/firebase-config.js', import.meta.url), 'utf8');

  assert.match(auth, /GoogleAuthProvider/);
  assert.match(auth, /browserLocalPersistence/);
  assert.match(auth, /setPersistence\(firebase\.auth, browserLocalPersistence\)/);
  assert.match(auth, /ensureAuthPersistence\(firebase\)[\s\S]*\.then/);
  assert.match(auth, /let unsubscribe = \(\) => \{\}/);
  assert.match(app, /Loading chats\.\.\./);
  assert.match(app, /if \(!authReady\) return/);
  assert.match(app, /let chatsLoading = false/);
  assert.match(app, /if \(!authReady \|\| currentAuthUser\) return/);
  assert.match(auth, /signInWithPopup/);
  assert.match(auth, /prompt: 'select_account'/);
  assert.match(auth, /signOut\(firebase\.auth\)/);
  assert.match(auth, /collection\(db, 'users'\)/);
  assert.match(auth, /subscribeAuthenticatedUsers/);
  assert.match(auth, /collection\(db, 'users'\)/);
  assert.match(auth, /const userRef = doc\(firebase\.db, 'users', user\.uid\)/);
  assert.match(auth, /await setDoc\(userRef, profile, \{ merge: true \}\)/);
  assert.match(auth, /lastLoginAt: serverTimestamp\(\)/);
  assert.match(auth, /onlineStatus: 'online'/);
  assert.match(auth, /normalizeOnlineStatus/);
  assert.match(auth, /allowedOnlineStatuses/);
  assert.match(auth, /dedupeGoogleUsers/);
  assert.match(auth, /seenEmails/);
  assert.doesNotMatch(auth, /user\.onlineStatus === 'online'/);
  assert.match(auth, /setUserOnlineStatus/);
  assert.match(app, /setUserOnlineStatus/);
  assert.match(app, /visibilitychange/);
  assert.match(app, /beforeunload/);
  assert.match(app, /renderPresenceStatus/);
  assert.match(app, /🟢 Online/);
  assert.match(app, /🌙 Away/);
  assert.match(app, /⚫ Offline/);
  assert.match(auth, /senderUid: user\.uid/);
  assert.match(auth, /senderEmail: user\.email/);
  assert.match(auth, /senderDisplayName:/);
  assert.match(auth, /const participants = \[user\.uid, contactUid\]\.sort\(\)/);
  assert.match(auth, /participants,/);
  assert.doesNotMatch(auth, /participants: \[user\.uid, contactUid\]/);
  assert.match(app, /data-auth-sign-in/);
  assert.match(app, /document\.querySelector\('\.signed-in-user'\)/);
  assert.match(app, /currentAuthUser\.email/);
  assert.match(app, /currentAuthUser/);
  assert.match(app, /createAuthenticatedContact/);
  assert.match(app, /friendSearchQuery/);
  assert.match(app, /renderFriendsInvitesPanel/);
  assert.match(app, /id="friendSearchForm"/);
  assert.match(app, /data-friend-search-input/);
  assert.match(app, /filterAuthenticatedUsers/);
  assert.match(app, /Only approved family and friends can chat here/);
  assert.doesNotMatch(app, /data-friend-search-submit/);
  assert.doesNotMatch(app, /subscribeUserByEmail/);
  assert.doesNotMatch(app, /Press Search to find or invite this Gmail/);
  assert.match(app, /reconcileAuthenticatedContacts/);
  assert.doesNotMatch(app, /placeholder="Aisha Friend"/);
  assert.match(config, /apiKey: 'AIzaSyCTwbG9VfUstguvtiEhCLWLiO2U1SZFoGM'/);
  assert.match(config, /projectId: 'kidswhatsapp-6fffb'/);
  assert.doesNotMatch(config, /apiKey: 'YOUR_/);
});

test('logout uses Firebase sign-out instead of fake local session state', () => {
  const app = readFileSync(new URL('../src/app.js', import.meta.url), 'utf8');
  const store = readFileSync(new URL('../src/chat-store.js', import.meta.url), 'utf8');

  assert.match(app, /async function handleGoogleLogout\(\)/);
  assert.match(app, /await logoutGoogleUser\(\)/);
  assert.match(app, /if \(finalAction === 'logout'\)[\s\S]*handleGoogleLogout\(\)/);
  assert.doesNotMatch(app, /let isLoggedOut = false/);
  assert.doesNotMatch(app, /data-login-again/);
  assert.doesNotMatch(app, /Logged in again/);
  assert.doesNotMatch(store, /This is a demo/);
});

test('Firestore rules require auth uid and sender identity to match request auth', () => {
  const rules = readFileSync(new URL('../firestore.rules', import.meta.url), 'utf8');

  assert.match(rules, /request\.auth != null/);
  assert.match(rules, /request\.auth\.uid == uid/);
  assert.match(rules, /validSelfProfileCreate\(uid\)/);
  assert.match(rules, /validSelfProfileUpdate\(uid\)/);
  assert.match(rules, /approvedUser\(request\.auth\.uid\)/);
  assert.match(rules, /onlineStatus in \['online', 'away', 'offline'\]/);
  assert.match(rules, /senderUid == request\.auth\.uid/);
  assert.match(rules, /senderEmail == request\.auth\.token\.email/);
  assert.match(rules, /participants\.hasAny\(\[request\.auth\.uid\]\)/);
  assert.match(rules, /function validConversationUpdate\(\)/);
  assert.match(rules, /request\.resource\.data\.participants == resource\.data\.participants/);
  assert.match(rules, /affectedKeys\(\)\.hasOnly\(\['updatedAt'\]\)/);
  assert.match(rules, /allow update: if validConversationUpdate\(\)/);
  assert.match(rules, /function validConversationReadReceiptUpdate\(conversationId\)/);
  assert.match(rules, /allow update: if validConversationReadReceiptUpdate\(conversationId\)/);
});
